#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branchName="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branchName" == "main" ] || [ "$branchName" == "staging" ]; then
  echo -e "\n🚫 Commit directly to main or staging branch is not allowed!\n" && exit 1
fi

cd ./shuffle

pnpm typecheck

npx lint-staged

pnpm test run