import autogenerateComments from "@/lib/autogenerateComments";
import { auth } from "@clerk/nextjs";
import { notFound } from "next/navigation";
import { NextRequest, NextResponse } from "next/server";

// POST /api/completions
// -----------------------------------------------------------------------------

export async function POST(request: NextRequest) {
  const { userId } = auth();
  if (!userId) {
    notFound();
  }

  const { title, question } = await request.json();

  const autogeneratedComments = await autogenerateComments({
    title,
    question,
  });

  return NextResponse.json(autogeneratedComments);
}
